my_string = input("финал лиги чемпионов")
print(my_string)
print(len("финал лиги чемпионов"))
print("финал лиги чемпионов".upper())
print("финал лиги чемпионов".upper().lower())
print("финал лиги чемпионов" .replace(" ",""))
print("финал лиги чемпионов"[0])
print("финал лиги чемпионов" [-1])